const BASE_URL = process.env.REACT_APP_TMDB_BASE_URL;
const API_KEY = process.env.REACT_APP_TMDB_API_KEY;
const BASE_IMAGE_URL = process.env.REACT_APP_TMDB_IMAGE_ORIGIN;
const SMALL_IMAGE_URL = process.env.REACT_APP_TMDB_IMAGE_SMALLER;

export { BASE_URL, API_KEY, BASE_IMAGE_URL, SMALL_IMAGE_URL };
